# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b61e2f5ff1bd06972b2b006db9783a79b890260810673cb003169d35c34e4135df32c3db0c6fadf56e6a6197da9ff037e0ffe4176495694058824d91e922b3

test:
  secret_key_base: 9f290691d255624e97b973988af81198db74ca1682420b14d77f81f94a750b6b07e2787602f9abca2355fcc4bd8f11bbc4510734b4c47395ca3130ea662ad82f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
